image: python:3.9.2-buster

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_prod:
  stage: deploy
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --verbose
  only:
    - tags