deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --verbose
  only:
    - tags